#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libibcm
Version  : 1.0.5
Release  : 1
URL      : https://www.openfabrics.org/downloads/rdmacm/libibcm-1.0.5.tar.gz
Source0  : https://www.openfabrics.org/downloads/rdmacm/libibcm-1.0.5.tar.gz
Summary  : Userspace InfiniBand Communication Manager.
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0
Requires: libibcm-lib
BuildRequires : libibverbs-dev

%description
libibcm provides a userspace InfiniBand Communication Managment library.

%package dev
Summary: dev components for the libibcm package.
Group: Development
Requires: libibcm-lib
Provides: libibcm-devel

%description dev
dev components for the libibcm package.


%package lib
Summary: lib components for the libibcm package.
Group: Libraries

%description lib
lib components for the libibcm package.


%prep
%setup -q -n libibcm-1.0.5

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/infiniband/cm.h
/usr/include/infiniband/cm_abi.h
/usr/lib64/*.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
